const test=require('node:test');const assert=require('node:assert/strict');
let C;try{C=require('../app/src/main/assets/core.js')}catch{}
const fresh=()=>C.newCampaign({name:'용사',job:'검사',world:'판타지',mode:'demo'});
const turn=(extra={})=>({narration:'이야기',choices:['탐색'],hpDelta:0,mpDelta:0,xpDelta:0,goldDelta:0,inventoryChanges:[],rewardId:'',location:'숲',quest:'마을 보호',companions:[],summary:'숲을 탐험했다.',...extra});
test('core contract exists',()=>assert.ok(C,'missing gameplay core'));
test('initial campaign is isolated with useful stats',()=>{const a=fresh(),b=fresh();assert.notEqual(a.id,b.id);assert.equal(a.hp,a.maxHp);assert.equal(a.mode,'demo');assert.ok(a.inventory.length)});
test('atomic turn preserves original on invalid delta',()=>{let s=fresh(),before=JSON.stringify(s);assert.throws(()=>C.applyTurn(s,'공격',turn({hpDelta:NaN}),10));assert.equal(JSON.stringify(s),before)});
test('clamps health and resources and levels from xp',()=>{let s=fresh(),n=C.applyTurn(s,'공격',turn({hpDelta:-s.maxHp,mpDelta:s.maxMp,goldDelta:-20,xpDelta:250}),20);assert.equal(s.turnCount,0);assert.equal(n.hp,0);assert.equal(n.mp,n.maxMp);assert.equal(n.gold,0);assert.ok(n.level>1);assert.ok(n.lastChanges.some(x=>x.includes('20')))});
test('repeated reward id cannot duplicate xp gold items',()=>{let s=fresh(),t=turn({rewardId:'chest-1',xpDelta:10,goldDelta:10,inventoryChanges:[{id:'gem',name:'보석',delta:1}]});s=C.applyTurn(s,'열기',t,10);let n=C.applyTurn(s,'열기',t,10);assert.equal(n.xp,s.xp);assert.equal(n.gold,s.gold);assert.equal(n.inventory.find(x=>x.id==='gem').qty,1)});
test('inventory removal and dangerous IDs',()=>{let s=fresh(),id=s.inventory[0].id;assert.equal(C.applyTurn(s,'사용',turn({inventoryChanges:[{id,name:'물약',delta:-s.inventory[0].qty}]}),10).inventory.some(x=>x.id===id),false);assert.throws(()=>C.applyTurn(s,'시도',turn({inventoryChanges:[{id:'__proto__',name:'악성',delta:1}]}),10))});
test('saves round trip and reject secrets malformed values oversized payload',()=>{let s=fresh();assert.deepEqual(C.importSave(C.exportSave(s)),s);assert.throws(()=>C.importSave('x'.repeat(2*1024*1024+1)));assert.throws(()=>C.importSave(JSON.stringify({...s,hp:Infinity})));assert.throws(()=>C.importSave(JSON.stringify({...s,apiKey:'secret'})))});
test('Responses handles output text usage refusals incomplete errors',()=>{let p=C.parseResponse({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(turn())}]}],usage:{input_tokens:3,output_tokens:4,total_tokens:7}});assert.equal(p.usage.totalTokens,7);for(let r of [{status:'incomplete'},{error:{message:'bad'}},{output:[{content:[{type:'refusal',refusal:'no'}]}]}])assert.throws(()=>C.parseResponse(r));assert.throws(()=>C.parseResponse({output_text:'{}'}))});
test('request has strict schema and bounded context and no secret',()=>{let s=fresh();s.messages=Array.from({length:100},(_,i)=>({role:'user',text:'행동 '+i}));let r=C.buildRequest(s,'탐색','gpt-6.1-sol',8);assert.equal(r.store,false);assert.equal(r.text.format.strict,true);assert.ok(r.max_output_tokens<=3500);assert.ok(!JSON.stringify(r).includes('행동 0"'));assert.equal(r.reasoning.effort,'low')});
test('history bounded and usage sums',()=>{let s=fresh();for(let i=0;i<70;i++)s=C.applyTurn(s,'탐색',turn({usage:{inputTokens:1,outputTokens:2,totalTokens:3}}),10);assert.equal(s.messages.length,120);assert.equal(s.usage.totalTokens,210)});
test('demo offers branching combat healing exploration and item use',()=>{let s=fresh();for(let action of ['탐색','대화','공격','휴식','물약 사용']){let t=C.demoTurn(s,action,12);assert.ok(t.narration.includes('연습'));assert.ok(t.choices.length);s=C.applyTurn(s,action,t,12)}assert.equal(s.turnCount,5)});
test('rejects invalid rolls actions and imported metadata',()=>{let s=fresh();assert.throws(()=>C.applyTurn(s,'공격',turn(),21));assert.throws(()=>C.applyTurn(s,'',turn(),10));assert.throws(()=>C.validateCampaign({...s,mode:'hacked'}));assert.throws(()=>C.validateCampaign({...s,inventory:[{id:'bad',name:'물건',qty:1.1}]}))});
test('nested save metadata cannot hide keys or executable fields',()=>{let s=fresh();assert.throws(()=>C.importSave(JSON.stringify({...s,inventory:[{...s.inventory[0],apiKey:'secret'}]})));assert.throws(()=>C.importSave(JSON.stringify({...s,messages:[{role:'assistant',text:'ok',html:'<script>'}]})));assert.throws(()=>C.validateCampaign({...s,usage:{...s.usage,key:'secret'}}))});
test('rejects duplicate inventory changes to avoid arbitrary overwrite',()=>{assert.throws(()=>C.applyTurn(fresh(),'사용',turn({inventoryChanges:[{id:'potion',name:'물약',delta:1},{id:'potion',name:'물약',delta:1}]}),10))});

test('rejects invalid costs and excessive turn deltas atomically',()=>{let s=fresh(),before=JSON.stringify(s);for(let t of [turn({xpDelta:-1}),turn({goldDelta:10001}),turn({hpDelta:s.maxHp+1}),turn({mpDelta:-s.maxMp-1}),turn({hpDelta:20,inventoryChanges:[{id:'potion',name:'물약',delta:-3}]})])assert.throws(()=>C.applyTurn(s,'사용',t,10));assert.equal(JSON.stringify(s),before)});
test('AI genre starts in chosen world and defeat requires recovery',()=>{let ai=C.newCampaign({name:'용사',job:'검사',world:'생존',mode:'ai'});assert.ok(ai.location.includes('생존'));assert.ok(!ai.messages[0].text.includes('달빛'));let s=fresh();s.hp=0;let attack=C.demoTurn(s,'공격',20);assert.equal(attack.xpDelta,0);assert.ok(attack.narration.includes('쓰러'));let recovered=C.applyTurn(s,'휴식',C.demoTurn(s,'휴식',10),10);assert.ok(recovered.hp>0)});
