const assert=require('node:assert/strict');
const {chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE||undefined,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('file://'+process.cwd()+'/app/src/main/assets/index.html');
 await page.getByRole('button',{name:'새로운 모험 시작'}).waitFor({timeout:2500});
 await page.getByRole('button',{name:'새로운 모험 시작'}).click();
 await page.getByLabel('캐릭터 이름').fill('오준');
 await page.getByRole('button',{name:'연습 모드',exact:true}).click();
 await page.getByRole('button',{name:'모험 시작',exact:true}).click();
 await page.getByPlaceholder('어떻게 행동할까? 자유롭게 적어봐.').fill('경비와 대화한다');
 await page.getByRole('button',{name:'행동 보내기'}).click();
 await page.getByText('경비 아린', {exact:false}).first().waitFor({timeout:3000});
 await page.getByRole('button',{name:'가방',exact:true}).click();
 await page.getByText('회복 물약',{exact:true}).waitFor();
 await page.reload();
 await page.getByRole('button',{name:'동료',exact:true}).click();
 await page.getByText('경비 아린',{exact:true}).waitFor();
 await page.getByRole('button',{name:'모험',exact:true}).click();
 await page.getByPlaceholder('어떻게 행동할까? 자유롭게 적어봐.').fill('<img src=x onerror="window.injected=true">');
 await page.getByRole('button',{name:'행동 보내기'}).click();
 await page.waitForFunction(()=>!document.querySelector('.thinking'));
 assert.equal(await page.evaluate(()=>window.injected),undefined);
 assert.equal(await page.locator('.message.user img').count(),0);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.deepEqual(errors,[]);
 await page.screenshot({path:'build/ui-chat.png',fullPage:true});
 await page.getByRole('button',{name:'모험 목록'}).click();
 await page.screenshot({path:'build/ui-home.png',fullPage:true});
 await page.getByRole('button',{name:'설정 열기'}).click();
 await page.getByText('API 사용료는 ChatGPT 구독과 별도',{exact:false}).waitFor();
 await page.getByLabel('OpenAI API 키').fill('sk-ui-test-not-a-real-key');
 await page.getByRole('button',{name:'설정 저장'}).click();
 assert.equal(await page.getByLabel('OpenAI API 키').inputValue(),'');
 assert.equal(await page.evaluate(()=>JSON.stringify(localStorage).includes('sk-ui-test')),false);
 await browser.close();console.log('UI smoke PASS: create, turn, bag, restore, companion, safe rendering, settings');
})().catch(e=>{console.error(e);process.exit(1)});
